---
title: "Newsletter of the Alaska Entomological Society"
date: "`r format(Sys.time(), '%B %e, %Y')`"
citeproc: false
section-refs-bibliography:
  - chokecherry_midge.bib
  - corrections.bib
csl: ../../share/pensoft-journals.csl
link-citations: true
params:
  volume: 15
  issue: 1
output:
  bookdown::pdf_book:
    latex_engine: pdflatex
    pandoc_args: 
      - --listings
      - --lua-filter=../../share/section-refs.lua
    toc: false
    toc_depth: 1
    number_sections: false
    includes:
      in_header: 
        - ../../share/preamble_Rmd.tex
      before_body:
        - ../../share/doc-prefix.tex
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  comment = "#>", echo = FALSE
)

pream <- readLines("../../share/preamble_Rmd_pre_sub.tex")
issueinfo <- paste0("Volume ", params$volume, ", Issue ", params$issue, ", ", format(Sys.time(), '%B %Y'))
pream <- gsub("issueinfo", issueinfo, pream)
write(pream, file = "../../share/preamble_Rmd.tex")

articles <- c("chokecherry_midge.Rmd", "corrections.Rmd")
```

```{r, child=articles}
```  
